#!/usr/bin/env python3
"""Generate Lean data (family + hints) for one-corridor families, from the C++ checker's `inspect` mode.

Usage: python3 gen_lean_hints.py <families.txt> <out.lean> <name>
families.txt: one family per line, 'vx vy bx by n' (one far block, no near blocks), e.g. from childdump P lines.
The hints (zones, switch times, certificate) are only hints: the Lean checker re-derives everything it uses.
"""
import sys, subprocess, re, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from indep_family import run

DIAG = {(2, 2): 'pp', (2, -2): 'pm', (-2, 2): 'mp', (-2, -2): 'mm'}


def inspect(vx, vy, bx, by, n):
    inp = f"1 {vx} {vy} 1 {bx} {by} 1 {n}\n"
    out = subprocess.run([os.environ.get('CALC', './calc'), 'inspect'], input=inp, capture_output=True, text=True, check=True).stdout
    m = re.search(r'verify: ok=(\d) why=(\S*) failp=\S+ T=(\d+) cert u=\((-?\d+),(-?\d+)\) s=(\d+)', out)
    ok, why, T, ux, uy, s = int(m[1]), m[2], int(m[3]), int(m[4]), int(m[5]), int(m[6])
    p = re.search(r'mu=(-?\d+) D=(-?\d+) C=(-?\d+) final_side=(-?\d+) transits:(.*)', out)
    D, C = int(p[2]), int(p[3])
    ms = [int(x) for x in re.findall(r'm=(\d+)', p[5])]
    return ok, why, T, (ux, uy), s, D, C, ms


def lean_pt(p):
    return f"⟨{p[0]}, {p[1]}⟩"


def main():
    src, dst, name = sys.argv[1], sys.argv[2], sys.argv[3]
    rows = []
    for line in open(src):
        a = line.split()
        if len(a) < 5: continue
        vx, vy, bx, by, n = map(int, a[:5])
        ok, why, T, u, s, D, C, ms = inspect(vx, vy, bx, by, n)
        assert ok == 1, (line, why)
        cells = [(bx + n * vx, by + n * vy)]
        X, Y, H, Rd, black, ft, fin, _ = run(cells, s + 105)
        A = min(u[0] * X[w] + u[1] * Y[w] for w in range(s, s + 105)) - 1
        rows.append((DIAG[(vx, vy)], (bx, by), n, D, C, ms, s, u, A))
    with open(dst, 'w') as f:
        f.write('import TwoBlack.Check\n\nnamespace TwoBlack\n\n')
        f.write(f'/-- {len(rows)} one-corridor families with checker hints (generated by gen_lean_hints.py). -/\n')
        f.write(f'def {name} : List (Fam1 × Hint1) := [\n')
        for i, (dg, b, n, D, C, ms, s, u, A) in enumerate(rows):
            sep = ',' if i + 1 < len(rows) else ''
            f.write(f'  (⟨.{dg}, [], [{lean_pt(b)}]⟩, ⟨{n}, {D}, {C}, {ms}, {s}, {lean_pt(u)}, {A}⟩){sep}\n')
        f.write(']\n\nend TwoBlack\n')
    print(f'wrote {len(rows)} families to {dst}')


if __name__ == '__main__':
    main()
