/-
  Lemma 6.3 for the 22 channel parents, discharged by the partition check on member 40 of each parent
  (generated by gen_lean_part.py).  The corridor hints are those of `level1Families`, except that the
  two-switch parent uses D = 52, so that the near/far threshold D + 16 = 68 of the one-step lemma is the
  checker's split index 10.
-/
import TwoBlack.PartCheck
import TwoBlack.Chan.All

namespace TwoBlack

/-- Block, corridor hint, partition hint. -/
def partHints : List (Pt × Hint1 × PartHint) := [
  (⟨-33, -7⟩, ⟨40, 21, 197, [12310], 15392, ⟨-2, -2⟩, 419⟩, ⟨14982, 15808, 219, .mm⟩),
  (⟨-34, -7⟩, ⟨40, 21, 195, [12310], 15600, ⟨-2, -2⟩, 427⟩, ⟨14983, 16016, 223, .mm⟩),
  (⟨-34, -6⟩, ⟨40, 21, 173, [12310], 19968, ⟨2, -2⟩, 97⟩, ⟨14984, 20384, 58, .pm⟩),
  (⟨-34, -8⟩, ⟨40, 21, 198, [12311], 15704, ⟨-2, -2⟩, 435⟩, ⟨14996, 16120, 227, .mm⟩),
  (⟨-35, -8⟩, ⟨40, 21, 151, [12311], 21632, ⟨-2, -2⟩, 441⟩, ⟨14997, 21944, 227, .mm⟩),
  (⟨-35, -7⟩, ⟨40, 21, 129, [12311], 27872, ⟨-2, 2⟩, 129⟩, ⟨14998, 28288, 74, .mp⟩),
  (⟨-33, -8⟩, ⟨40, 21, 173, [12310], 23712, ⟨-2, 2⟩, 169⟩, ⟨15001, 24128, 94, .mp⟩),
  (⟨-34, -9⟩, ⟨40, 21, 169, [12311], 21008, ⟨-2, 2⟩, 93⟩, ⟨15007, 21424, 56, .mp⟩),
  (⟨-33, -11⟩, ⟨40, 21, 167, [12320], 18616, ⟨2, -2⟩, 97⟩, ⟨15014, 18928, 54, .pm⟩),
  (⟨-34, -11⟩, ⟨40, 21, 188, [12320], 17264, ⟨2, -2⟩, 103⟩, ⟨15015, 17576, 58, .pm⟩),
  (⟨-34, -10⟩, ⟨40, 21, 188, [12320], 17264, ⟨2, -2⟩, 97⟩, ⟨15016, 17680, 58, .pm⟩),
  (⟨-34, -12⟩, ⟨40, 21, 149, [12321], 21736, ⟨-2, 2⟩, 101⟩, ⟨15024, 22048, 56, .mp⟩),
  (⟨-35, -12⟩, ⟨40, 21, 169, [12321], 22776, ⟨-2, 2⟩, 137⟩, ⟨15025, 23088, 74, .mp⟩),
  (⟨-35, -11⟩, ⟨40, 21, 196, [12321], 17368, ⟨2, -2⟩, 103⟩, ⟨15026, 17680, 58, .pm⟩),
  (⟨-33, -12⟩, ⟨40, 21, 161, [12320], 17680, ⟨-2, -2⟩, 435⟩, ⟨15029, 17992, 223, .mm⟩),
  (⟨-33, -13⟩, ⟨40, 21, 148, [12321], 48256, ⟨-2, -2⟩, 495⟩, ⟨15030, 48672, 257, .mm⟩),
  (⟨-34, -13⟩, ⟨40, 21, 149, [12321], 22672, ⟨-2, 2⟩, 113⟩, ⟨15031, 23088, 66, .mp⟩),
  (⟨-32, -13⟩, ⟨40, 21, 187, [12320], 23712, ⟨-2, -2⟩, 489⟩, ⟨15039, 24024, 251, .mm⟩),
  (⟨-32, -14⟩, ⟨40, 21, 165, [12321], 31304, ⟨-2, 2⟩, 125⟩, ⟨15040, 31720, 72, .mp⟩),
  (⟨-33, -14⟩, ⟨40, 52, 153, [12321, 68327], 80184, ⟨-2, 2⟩, 169⟩, ⟨15041, 80600, 94, .mp⟩),
  (⟨-32, -12⟩, ⟨40, 21, 179, [12320], 18928, ⟨-2, -2⟩, 465⟩, ⟨15044, 19240, 239, .mm⟩),
  (⟨-31, -13⟩, ⟨40, 21, 198, [12320], 15496, ⟨-2, -2⟩, 427⟩, ⟨15058, 15912, 223, .mm⟩)
]

def partHintFor (F : Fam1) : Option (Hint1 × PartHint) :=
  match partHints.find? (fun e => [e.1] == F.far) with
  | some e => some e.2
  | none => none

def partOK (F : Fam1) : Bool :=
  match partHintFor F with
  | some (H, P) => checkPart F H P (kidsIn chanTable F)
  | none => false

theorem part_checks : level1Families.all (fun p => partOK p.1) = true := by native_decide

/-- **Lemma 6.3 for the 22 channel parents** (the hypothesis `hpart` of `two_black_final`). -/
theorem hpart_proved : ∀ p ∈ level1Families, ChildPartition1 p.1 40 (kidsIn chanTable p.1) := by
  intro p hp
  have h := List.all_eq_true.mp part_checks p hp
  unfold partOK at h
  split at h
  · next H P _ => exact checkPart_sound p.1 H P _ h
  · exact absurd h (by simp)

end TwoBlack
